### ISSUE TITLE
Code snippets on multiple lines

### ISSUE THREAD

**Issue by marcochiesi** [stephenharris/wp-readme-to-markdown#7]
WP and Github have different syntax for code snippets on multiple lines. Would it be possible to convert them? I suppose it would be sufficient to replace lines containing only a single backquote with three backquotes.

See example:
- WP: https://wordpress.org/plugins/black-studio-tinymce-widget/faq/ (see exxamples at the bottom of the page)
- Git: https://github.com/black-studio/black-studio-tinymce-widget/blob/master/README.md#how-to-customize-widget-html-markup

**Comment by stephenharris** [comment]
Finally got round to doing this :). Thanks @marcochiesi for your comments regarding the global modifier. 

This latest update formats codeblocks according to standard markdown (rather than wrapping in HTML tags or GitHub's three backtics. Although some people (including myself) prefer backtics to indentation, this is an auto-generated file which shouldn't normally be edited, so all that matters is that it is properly formatted. 

Feedback welcome, else in a few days I'm going to hit publish on this for the npm repository.

### Caveats

As noted in the readme there is some caveats to this. I noticed some unexpected behaviour regarding backtics and codeblocks (according to the validator linked to above). Here's summary:

- **Inline code** must be enclosed by single backtics, and must not contain an empty line.

- **Codeblocks** should be enclosed by single backtics, the first one of which must be the first character on the line **and** the enclosed content must contain a newline.

Four examples to illustrate

```
`inline` and this is `also inline`

`function thisIsACodeBlock(){
}`

This `function isInline(){
}`

This `function isNeither(){

}`
```

**So what's the caveat?**

Currently this plug-in ignores examples like (2). This may change, but for the time being please ensure your readme.txt code blocks are formatted so that the backtics are on their own line:

```
`
function thisIsACodeBlock(){
}
`
```
